policy: "MlpPolicy"
learning_rate: 0.001
gamma: 0.98
buffer_size: 500000
learning_starts: 1000
batch_size: 128
tau: 0.01
train_freq: 4
gradient_steps: 2
action_noise: 0.2
total_timesteps: 500000
wandb_project: "assistive-walker-ddpg"
wandb_entity: "your_team"
device: "auto"
