policy: "MlpPolicy"
learning_rate: 0.0003
gamma: 0.99
buffer_size: 1000000
learning_starts: 100
batch_size: 256
tau: 0.005
train_freq: 1
gradient_steps: 1
action_noise: 0.1
total_timesteps: 300000
wandb_project: "assistive-walker-ddpg"
wandb_entity: "your_team"
device: "auto"
