policy: "MlpPolicy"
learning_rate: 0.00015
gamma: 0.995
buffer_size: 2000000
learning_starts: 5000
batch_size: 512
tau: 0.002
train_freq: 1
gradient_steps: 1
action_noise: 0.05
total_timesteps: 500000
wandb_project: "assistive-walker-ddpg"
wandb_entity: "your_team"
device: "auto"
