
#Low Derivative
wandb_project: "assistive-walker-pid"
Kp: 8.2
Ki: 0.4
Kd: 2.5
max_episodes: 30
settling_threshold: 0.05
dt: 0.05


# #High Integral
# wandb_project: "assistive-walker-pid"
# Kp: 7.0
# Ki: 2.0
# Kd: 2.0
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05


# #Conservative
# wandb_project: "assistive-walker-pid"
# Kp: 4.0
# Ki: 0.1
# Kd: 1.2
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05



# #baseline
# wandb_project: "assistive-walker-pid"
# Kp: 8.2
# Ki: 0.4
# Kd: 2.5
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05


# #Agressive
# wandb_project: "assistive-walker-pid"
# Kp: 15.0
# Ki: 0.7
# Kd: 4.0
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05



