
# wandb_project: "assistive-walker-test"
# Kp: 13.5
# Ki: 4.2
# Kd: 10.7
# max_episodes: 100
# settling_threshold: 0.05
# dt: 0.05
# max_steps: 1000

wandb_project: "Final_Test_AssistiveWalker"
Kp: 18.27
Ki: 13.91
Kd: 3.224
max_episodes: 100
settling_threshold: 0.05
dt: 0.05
max_steps: 1000

# wandb_project: "assistive-walker-test"
# Kp: 50.00
# Ki: 110.00
# Kd: 3.5
# max_episodes: 100
# settling_threshold: 0.05
# dt: 0.05
# max_steps: 1000


# #High Integral
# wandb_project: "assistive-walker-pid"
# Kp: 7.0
# Ki: 2.0
# Kd: 2.0
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05


# #Conservative
# wandb_project: "assistive-walker-pid"
# Kp: 4.0
# Ki: 0.1
# Kd: 1.2
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05



# #baseline
# wandb_project: "assistive-walker-pid"
# Kp: 8.2
# Ki: 0.4
# Kd: 2.5
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05


# #Agressive
# wandb_project: "assistive-walker-pid"
# Kp: 15.0
# Ki: 0.7
# Kd: 4.0
# max_episodes: 30
# settling_threshold: 0.05
# dt: 0.05



