policy: "MlpPolicy"
learning_rate: 0.0002
gamma: 0.98
gae_lambda: 0.90
batch_size: 512
n_epochs: 15
clip_range: 0.18
net_arch: [256, 128]
ent_coef: 0.02
max_grad_norm: 0.6
use_sde: True
sde_sample_freq: 1
policy_kwargs:
  ortho_init: False
  log_std_init: -0.7
total_timesteps: 3000000
