wandb_project: "assistive-walker-test"
wandb_entity: "your_wandb_team"

learning_rate: 0.12
gamma: 0.98
epsilon: 1.0
epsilon_decay: 0.995
min_epsilon: 0.02

bins: [10, 10, 10, 10, 10, 10, 10]
obs_low: [-3.14, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5]
obs_high: [3.14, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5]

total_episodes: 6000
max_steps_per_episode: 1200
solved_reward: 950
seed: 42
