wandb_project: "assistive-walker-test"
wandb_entity: "your_wandb_team"

learning_rate: 0.08
gamma: 0.97
epsilon: 1.0
epsilon_decay: 0.9995
min_epsilon: 0.1

bins: [8, 8, 8, 8, 8, 8, 8]
obs_low: [-3.14, -1.5, -1.5, -1.5, -1.5, -1.5, -1.5]
obs_high: [3.14, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5]

total_episodes: 4000
max_steps_per_episode: 800
solved_reward: 900
seed: 21
