
#Training Slow (More Episodes, Conservative Learning)
wandb_project: "Q-Learning-AssistiveWalker"
wandb_entity: "your_wandb_team"

learning_rate: 0.05
gamma: 0.995
epsilon: 1.0
epsilon_decay: 0.9995
min_epsilon: 0.01

bins: [8, 8, 8, 8, 8, 8, 8]
obs_low: [-3.14, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
obs_high: [3.14, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

total_episodes: 20000
max_steps_per_episode: 1200
solved_reward: 450
