#Fast Training (Aggressive Exploration, Fewer Episodes)

wandb_project: "Q-Learning-AssistiveWalker"
wandb_entity: "your_wandb_team"

learning_rate: 0.2
gamma: 0.97
epsilon: 0.8
epsilon_decay: 0.995
min_epsilon: 0.10

bins: [8, 8, 8, 8, 8, 8, 8]
obs_low: [-3.14, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
obs_high: [3.14, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

total_episodes: 2000
max_steps_per_episode: 800
solved_reward: 350
