wandb_project: "assistive-walker-test"
wandb_entity: "your_wandb_team"

learning_rate: 0.15
gamma: 0.98
epsilon: 1.0
epsilon_decay: 0.990
min_epsilon: 0.01

bins: [10, 10, 10, 10, 10, 10, 10]
obs_low: [-3.14, -2.2, -2.2, -2.2, -2.2, -2.2, -2.2]
obs_high: [3.14, 2.2, 2.2, 2.2, 2.2, 2.2, 2.2]

total_episodes: 7000
max_steps_per_episode: 1000
solved_reward: 1050
seed: 7
