wandb_project: "Q-Learning-AssistiveWalker"
wandb_entity: "your_wandb_team"

learning_rate: 0.09
gamma: 0.99
epsilon: 1.0
epsilon_decay: 0.9992
min_epsilon: 0.03

bins: [14, 14, 14, 14, 14, 14, 14]
obs_low: [-3.5, -3.0, -3.0, -3.0, -3.0, -3.0, -3.0]
obs_high: [3.5, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]

total_episodes: 8000
max_steps_per_episode: 1200
solved_reward: 1100
seed: 99
