#Different Bin Discretization (Coarse State Representation)

wandb_project: "Q-Learning-AssistiveWalker"

learning_rate: 0.1
gamma: 0.99
epsilon: 1.0
epsilon_decay: 0.999
min_epsilon: 0.05

bins: [4, 6, 6, 4, 4, 4, 4]  # Fewer bins for some dimensions
obs_low: [-3.14, -2.0, -2.0, -2.0, -2.0, -2.0, -2.0]
obs_high: [3.14, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

total_episodes: 5000
max_steps_per_episode: 1000
solved_reward: 400
