policy: "MlpPolicy"
learning_rate: 0.001
gamma: 0.98
buffer_size: 500000
learning_starts: 1000
batch_size: 128
tau: 0.01
ent_coef: 0.2
use_sde: False
train_freq: 4
gradient_steps: 2
target_update_interval: 2
action_noise: 0.2
total_timesteps: 500000
wandb_project: "cartpole-sac"
device: "auto"