policy: "MlpPolicy"
learning_rate: 0.00015
gamma: 0.995
buffer_size: 2000000
learning_starts: 5000
batch_size: 512
tau: 0.002
ent_coef: "auto_0.1"
use_sde: True
train_freq: 1
gradient_steps: 1
target_update_interval: 1
action_noise: 0.05
total_timesteps: 1000000
wandb_project: "walker-sac-stable"
device: "auto"