# =========================
# PPO Training Config Set 3
# =========================
policy: "MlpPolicy"
learning_rate: 0.0001
gamma: 0.995
batch_size: 32
n_steps: 4096
ent_coef: 0.005
clip_range: 0.15
n_epochs: 15
gae_lambda: 0.98
max_grad_norm: 0.3
vf_coef: 0.7
device: "auto"
total_timesteps: 300000
seed: 99
eval_episodes: 100
max_steps: 5000