# ===========================
# SAC Config Set 3: Conservative, Robust
# ===========================
policy: "MlpPolicy"
learning_rate: 0.0001
buffer_size: 2000000
learning_starts: 20000
batch_size: 512
tau: 0.002
gamma: 0.995
ent_coef: "auto"
train_freq: 1
gradient_steps: 1
use_sde: True
device: "auto"
total_timesteps: 3000000

seed: 9999
eval_episodes: 100
max_steps: 5000