# ===========================
# SAC Config Set 1: Baseline
# ===========================
policy: "MlpPolicy"
learning_rate: 0.0003
buffer_size: 1000000
learning_starts: 10000
batch_size: 256
tau: 0.005
gamma: 0.99
ent_coef: "auto"
train_freq: 1
gradient_steps: 1
use_sde: False
device: "auto"
total_timesteps: 3000000


seed: 423

eval_episodes: 100
max_steps: 5000


