# ===========================
# SAC Config Set 2: Fast Learning, Higher Entropy
# ===========================
policy: "MlpPolicy"
learning_rate: 0.001
buffer_size: 500000
learning_starts: 5000
batch_size: 128
tau: 0.01
gamma: 0.98
ent_coef: 0.2
train_freq: 2
gradient_steps: 2
use_sde: False
device: "auto"
total_timesteps: 500000

seed: 124
eval_episodes: 100
max_steps: 5000