# configs/qlearning_test.yaml

env: CartPole-v1
seed: 42
total_episodes: 2000
eval_episodes: 100  # Add this line
max_steps: 500

learning_rate: 0.1
discount_factor: 0.99
epsilon: 1.0
epsilon_decay: 0.995
epsilon_min: 0.01
bins: [6, 12, 6, 12]
model_path: logs/training_metadata.pkl
algo: qlearning
wandb:
  project_name: cartpole-testing
  experiment_name: qlearning_test
  log_model: True
  log_wandb: True
  log_interval: 10
  save_model: True
  save_interval: 100
  save_path: logs/training_metadata.pkl
  load_model: True
  load_path: models/q_table.pkl
  log_wandb: True