policy: "MlpPolicy"
learning_rate: 1e-3
gamma: 0.99
tau: 0.005
batch_size: 256
buffer_size: 1000000
train_freq: 1
gradient_steps: 4
# action_noise: 0.1
total_timesteps: 100_000
batch_size: 32
seed: 43
eval_episodes: 1000
max_steps: 200
