policy: "MlpPolicy"
learning_rate: 1e-3
gamma: 0.99
tau: 0.005
batch_size: 64
buffer_size: 1000000
train_freq: 1
gradient_steps: 1
action_noise: 0.1
total_timesteps: 300_000
buffer_size: 100000
batch_size: 32
seed: 43
eval_episodes: 100
max_steps: 200
