policy: "MlpPolicy"
learning_rate: 1e-3
gamma: 0.99
buffer_size: 100000
learning_starts: 1000
train_freq: 4
batch_size: 32
target_update_interval: 1000
total_timesteps: 100_000
seed: 42
eval_episodes: 100
max_steps: 200