
policy: "MlpPolicy"             # MLP policy
learning_rate: 0.0001           # Learning rate
gamma: 0.99                     # Discount factor
tau: 0.95                       # GAE decay factor
batch_size: 128                 # Larger batch size for more stable training
buffer_size: 2000000            # Larger buffer size for more experience storage
train_freq: 8                   # More frequent training
gradient_steps: 8               # More gradient steps per update
total_timesteps: 1000000        # More timesteps for training
policy_kwargs:
    net_arch: [128, 128]          # Larger network architecture
seed: 42                         # Random seed for reproducibility
tensorboard_log: "./ppo_tensorboard/"
eval_episodes: 1000              # Number of episodes for evaluation
max_steps: 500                  # Max steps per episode

#PPO with Higher Batch Size and Buffer Size