env: "CartPole-v1"
algo: "q_learning"
bins: 10
total_episodes: 10000
max_steps: 200
learning_rate: 0.1
discount_factor: 0.99
epsilon: 1.0
epsilon_min: 0.05
epsilon_decay: 0.995
alpha_schedule: "decay"
checkpoint_interval: 1000
seed: 42
resume_from: null
