env: "CartPole-v1"
algo: "q_learning"
bins: 20
total_episodes: 100000
learning_rate: 0.05
discount_factor: 0.99
epsilon: 1.0
min_epsilon: 0.01
max_steps: 200
epsilon_decay: 0.99999
alpha_schedule: "decay"
checkpoint_interval: 1000
seed: 42
resume_from: null
gamma: 0.99
max_steps_per_episode: 200
bins: [20, 20, 20, 20]
obs_low: [-25, -5.0, -0.418, -5.0]
obs_high: [25, 5.0, 0.418, 5.0]
eval_episodes: 1000